#pragma once

#define SDL2PP_MAJOR_VERSION @SDL2PP_MAJOR_VERSION@
#define SDL2PP_MINOR_VERSION @SDL2PP_MINOR_VERSION@
#define SDL2PP_PATCH_VERSION @SDL2PP_PATCH_VERSION@

#define SDL2PP_VERSION "@SDL2PP_VERSION@"

#define SDL2PP_WITH_IMAGE
#define SDL2PP_WITH_TTF
#define SDL2PP_WITH_MIXER
//#define SDL2PP_WITH_EXPERIMENTAL_OPTIONAL